"""Description of changes

Revision ID: 23d26a5b1eef
Revises: eb7507e10d23
Create Date: 2023-09-05 16:20:00.721001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d26a5b1eef'
down_revision = 'eb7507e10d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SINGLE', 'DOUBLE', name='roomtype'),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('date_registered')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('SINGLE', 'DOUBLE', name='roomtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
